### ISSUE TITLE
Version of the installation package

### ISSUE THREAD

**Issue by fenfenfenfan** [dvirsamuel/SeedSelect#2]
Hello, thank you for your wonderful work!！
I met some problems when running your demo, it may be caused by conflicting versions of some installation packages. Can you share the requirements.txt or some information about the versions of the packages? Thanks a lot!!

**Comment by dvirsamuel** [comment]
Hey,
Here is a list of the major package versions used in our project:

torch=1.11.0a0+17540c5=pypi_0
torchtext=0.12.0a0=pypi_0
torchvision=0.12.0a0=pypi_0
tqdm=4.62.3=pyhd8ed1ab_0
diffusers=0.16.1=pypi_0
numpy=1.23.2=pypi_0
pillow=8.1.2=pypi_0
open-clip-torch=2.7.0=pypi_0
pytorch-lightning=1.6.0=pypi_0
transformers=4.28.1=pypi_0
matplotlib=3.5.1=pypi_0
matplotlib-inline=0.1.3=pyhd8ed1ab_0
