### ISSUE TITLE
About the Computing Distribution of Concepts in LAION

### ISSUE THREAD

**Issue by Uhoo0125** [dvirsamuel/SeedSelect#6]
Hello, thanks for your great job!

I'm very interested in the "Computing Distribution of Concepts in LAION datasets" mentioned in the paper. These analyses are valuable for improving the alignment in text-to-image generation. 

Would you like to share those results?

**Comment by dvirsamuel** [comment]
Thank you for your interest in our work.
The data will be published soon.

Thank you
